#############################################################################
# Makefile for building: sqlitenew
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  sqlitenew.pro
# Template: subdirs
# Command: D:\Qt\5.15.2\msvc2019_64\bin\qmake.exe -o Makefile sqlitenew.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\5.15.2\msvc2019_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\5.15.2\msvc2019_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\5.15.2\msvc2019_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-libs-antlr-2-7-7-antlr-pro \
		sub-libs-qhexedit-qhexedit-pro \
		sub-libs-qcustomplot-source-qcustomplot-pro \
		sub-libs-qscintilla-Qt4Qt5-qscintilla-pro \
		sub-libs-sqlite3-sqlite3-pro \
		sub-src


sub-libs-antlr-2-7-7-antlr-pro-qmake_all:  FORCE
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	cd libs\antlr-2.7.7\ && $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && $(MAKE) -f Makefile.antlr qmake_all
sub-libs-antlr-2-7-7-antlr-pro: $(MAKEFILE) FORCE
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr
sub-libs-antlr-2-7-7-antlr-pro-make_first: FORCE
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr 
sub-libs-antlr-2-7-7-antlr-pro-all: FORCE
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr all
sub-libs-antlr-2-7-7-antlr-pro-clean: FORCE
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr clean
sub-libs-antlr-2-7-7-antlr-pro-distclean: FORCE
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr distclean
sub-libs-antlr-2-7-7-antlr-pro-install_subtargets: FORCE
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr install
sub-libs-antlr-2-7-7-antlr-pro-uninstall_subtargets: FORCE
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr uninstall
sub-libs-qhexedit-qhexedit-pro-qmake_all:  FORCE
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	cd libs\qhexedit\ && $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && $(MAKE) -f Makefile qmake_all
sub-libs-qhexedit-qhexedit-pro: $(MAKEFILE) FORCE
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-libs-qhexedit-qhexedit-pro-make_first: FORCE
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-libs-qhexedit-qhexedit-pro-all: FORCE
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-libs-qhexedit-qhexedit-pro-clean: FORCE
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-libs-qhexedit-qhexedit-pro-distclean: FORCE
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-libs-qhexedit-qhexedit-pro-install_subtargets: FORCE
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-libs-qhexedit-qhexedit-pro-uninstall_subtargets: FORCE
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-libs-qcustomplot-source-qcustomplot-pro-qmake_all:  FORCE
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	cd libs\qcustomplot-source\ && $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && $(MAKE) -f Makefile.qcustomplot qmake_all
sub-libs-qcustomplot-source-qcustomplot-pro: $(MAKEFILE) FORCE
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot
sub-libs-qcustomplot-source-qcustomplot-pro-make_first: FORCE
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot 
sub-libs-qcustomplot-source-qcustomplot-pro-all: FORCE
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot all
sub-libs-qcustomplot-source-qcustomplot-pro-clean: FORCE
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot clean
sub-libs-qcustomplot-source-qcustomplot-pro-distclean: FORCE
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot distclean
sub-libs-qcustomplot-source-qcustomplot-pro-install_subtargets: FORCE
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot install
sub-libs-qcustomplot-source-qcustomplot-pro-uninstall_subtargets: FORCE
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot uninstall
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-qmake_all:  FORCE
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	cd libs\qscintilla\Qt4Qt5\ && $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && $(MAKE) -f Makefile.qscintilla qmake_all
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro: $(MAKEFILE) FORCE
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-make_first: FORCE
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla 
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-all: FORCE
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla all
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-clean: FORCE
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla clean
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-distclean: FORCE
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla distclean
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-install_subtargets: FORCE
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla install
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-uninstall_subtargets: FORCE
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla uninstall
sub-libs-sqlite3-sqlite3-pro-qmake_all:  FORCE
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	cd libs\sqlite3\ && $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && $(MAKE) -f Makefile qmake_all
sub-libs-sqlite3-sqlite3-pro: $(MAKEFILE) FORCE
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-libs-sqlite3-sqlite3-pro-make_first: FORCE
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-libs-sqlite3-sqlite3-pro-all: FORCE
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-libs-sqlite3-sqlite3-pro-clean: FORCE
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-libs-sqlite3-sqlite3-pro-distclean: FORCE
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-libs-sqlite3-sqlite3-pro-install_subtargets: FORCE
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-libs-sqlite3-sqlite3-pro-uninstall_subtargets: FORCE
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-src-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f Makefile qmake_all
sub-src: $(MAKEFILE) FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-src-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-src-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-src-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-src-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall

Makefile: sqlitenew.pro D:\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf D:\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_pre.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\common\angle.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-desktop.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-vulkan.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-desktop.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\qconfig.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_functions.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_config.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-version.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\toolchain.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\default_pre.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\default_pre.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\resolve_config.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\default_post.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qtquickcompiler.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\precompile_header.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\warn_on.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qmake_use.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\file_copies.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\testcase_targets.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exceptions.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\yacc.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\lex.prf \
		sqlitenew.pro
	$(QMAKE) -o Makefile sqlitenew.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_pre.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\common\angle.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-desktop.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-vulkan.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-desktop.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\qconfig.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_edid_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_egl_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_theme_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_functions.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_config.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_post.prf:
.qmake.stash:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-version.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\toolchain.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\default_pre.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\default_pre.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\resolve_config.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\default_post.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qtquickcompiler.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\precompile_header.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\warn_on.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qmake_use.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\file_copies.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\testcase_targets.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exceptions.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\yacc.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\lex.prf:
sqlitenew.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile sqlitenew.pro -spec win32-msvc "CONFIG+=qtquickcompiler"

qmake_all: sub-libs-antlr-2-7-7-antlr-pro-qmake_all sub-libs-qhexedit-qhexedit-pro-qmake_all sub-libs-qcustomplot-source-qcustomplot-pro-qmake_all sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-qmake_all sub-libs-sqlite3-sqlite3-pro-qmake_all sub-src-qmake_all FORCE

make_first: sub-libs-antlr-2-7-7-antlr-pro-make_first sub-libs-qhexedit-qhexedit-pro-make_first sub-libs-qcustomplot-source-qcustomplot-pro-make_first sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-make_first sub-libs-sqlite3-sqlite3-pro-make_first sub-src-make_first  FORCE
all: sub-libs-antlr-2-7-7-antlr-pro-all sub-libs-qhexedit-qhexedit-pro-all sub-libs-qcustomplot-source-qcustomplot-pro-all sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-all sub-libs-sqlite3-sqlite3-pro-all sub-src-all  FORCE
clean: sub-libs-antlr-2-7-7-antlr-pro-clean sub-libs-qhexedit-qhexedit-pro-clean sub-libs-qcustomplot-source-qcustomplot-pro-clean sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-clean sub-libs-sqlite3-sqlite3-pro-clean sub-src-clean  FORCE
distclean: sub-libs-antlr-2-7-7-antlr-pro-distclean sub-libs-qhexedit-qhexedit-pro-distclean sub-libs-qcustomplot-source-qcustomplot-pro-distclean sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-distclean sub-libs-sqlite3-sqlite3-pro-distclean sub-src-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-libs-antlr-2-7-7-antlr-pro-install_subtargets sub-libs-qhexedit-qhexedit-pro-install_subtargets sub-libs-qcustomplot-source-qcustomplot-pro-install_subtargets sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-install_subtargets sub-libs-sqlite3-sqlite3-pro-install_subtargets sub-src-install_subtargets FORCE
uninstall_subtargets: sub-libs-antlr-2-7-7-antlr-pro-uninstall_subtargets sub-libs-qhexedit-qhexedit-pro-uninstall_subtargets sub-libs-qcustomplot-source-qcustomplot-pro-uninstall_subtargets sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-uninstall_subtargets sub-libs-sqlite3-sqlite3-pro-uninstall_subtargets sub-src-uninstall_subtargets FORCE

sub-libs-antlr-2-7-7-antlr-pro-debug:
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr debug
sub-libs-qhexedit-qhexedit-pro-debug:
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-libs-qcustomplot-source-qcustomplot-pro-debug:
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot debug
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-debug:
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla debug
sub-libs-sqlite3-sqlite3-pro-debug:
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-src-debug:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
debug: sub-libs-antlr-2-7-7-antlr-pro-debug sub-libs-qhexedit-qhexedit-pro-debug sub-libs-qcustomplot-source-qcustomplot-pro-debug sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-debug sub-libs-sqlite3-sqlite3-pro-debug sub-src-debug

sub-libs-antlr-2-7-7-antlr-pro-release:
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr release
sub-libs-qhexedit-qhexedit-pro-release:
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-libs-qcustomplot-source-qcustomplot-pro-release:
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot release
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-release:
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla release
sub-libs-sqlite3-sqlite3-pro-release:
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-src-release:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
release: sub-libs-antlr-2-7-7-antlr-pro-release sub-libs-qhexedit-qhexedit-pro-release sub-libs-qcustomplot-source-qcustomplot-pro-release sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-release sub-libs-sqlite3-sqlite3-pro-release sub-src-release

sub-libs-antlr-2-7-7-antlr-pro-check:
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr check
sub-libs-qhexedit-qhexedit-pro-check:
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-libs-qcustomplot-source-qcustomplot-pro-check:
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot check
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-check:
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla check
sub-libs-sqlite3-sqlite3-pro-check:
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-src-check:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
check: sub-libs-antlr-2-7-7-antlr-pro-check sub-libs-qhexedit-qhexedit-pro-check sub-libs-qcustomplot-source-qcustomplot-pro-check sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-check sub-libs-sqlite3-sqlite3-pro-check sub-src-check

sub-libs-antlr-2-7-7-antlr-pro-benchmark:
	@if not exist libs\antlr-2.7.7\ mkdir libs\antlr-2.7.7\ & if not exist libs\antlr-2.7.7\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\antlr-2.7.7\ && ( if not exist Makefile.antlr $(QMAKE) -o Makefile.antlr C:\Users\User\Desktop\anotherSQLIte\libs\antlr-2.7.7\antlr.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.antlr benchmark
sub-libs-qhexedit-qhexedit-pro-benchmark:
	@if not exist libs\qhexedit\ mkdir libs\qhexedit\ & if not exist libs\qhexedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qhexedit\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\qhexedit\qhexedit.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-libs-qcustomplot-source-qcustomplot-pro-benchmark:
	@if not exist libs\qcustomplot-source\ mkdir libs\qcustomplot-source\ & if not exist libs\qcustomplot-source\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qcustomplot-source\ && ( if not exist Makefile.qcustomplot $(QMAKE) -o Makefile.qcustomplot C:\Users\User\Desktop\anotherSQLIte\libs\qcustomplot-source\qcustomplot.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qcustomplot benchmark
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-benchmark:
	@if not exist libs\qscintilla\Qt4Qt5\ mkdir libs\qscintilla\Qt4Qt5\ & if not exist libs\qscintilla\Qt4Qt5\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qscintilla\Qt4Qt5\ && ( if not exist Makefile.qscintilla $(QMAKE) -o Makefile.qscintilla C:\Users\User\Desktop\anotherSQLIte\libs\qscintilla\Qt4Qt5\qscintilla.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile.qscintilla benchmark
sub-libs-sqlite3-sqlite3-pro-benchmark:
	@if not exist libs\sqlite3\ mkdir libs\sqlite3\ & if not exist libs\sqlite3\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\sqlite3\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\libs\sqlite3\sqlite3.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-src-benchmark:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\User\Desktop\anotherSQLIte\src\src.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-libs-antlr-2-7-7-antlr-pro-benchmark sub-libs-qhexedit-qhexedit-pro-benchmark sub-libs-qcustomplot-source-qcustomplot-pro-benchmark sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-benchmark sub-libs-sqlite3-sqlite3-pro-benchmark sub-src-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

